# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# -----------------
# CA (CSR with CA extensions -> self-signed CA cert)
# -----------------
- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_key_filename }}"
    size: 4096
    type: RSA
    mode: '0600'

- name: Generate CA CSR with CA extensions
  community.crypto.openssl_csr:
    path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_csr_filename }}"
    privatekey_path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_key_filename }}"
    common_name: "{{ tls_ca_common_name }}"
    basic_constraints:
      - "CA:TRUE"
    key_usage:
      - keyCertSign
      - cRLSign

- name: Self-sign the CA CSR
  community.crypto.x509_certificate:
    path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_cert_filename }}"
    csr_path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_csr_filename }}"
    privatekey_path: "{{ tls_local_certs_dir }}/{{ tls_local_ca_key_filename }}"
    provider: selfsigned
    # selfsigned_not_after: "+10y"
