# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Print upload details
  ansible.builtin.debug:
    msg:
      - "Uploading multi-domain key and cert"
      - "   Key source: {{ tls_pki_md_key_file_local }}"
      - "   Key destination: {{ tls_pki_md_key_file_dest }}"
      - "   Cert source: {{ tls_pki_md_cert_file_local }}"
      - "   Cert destination: {{ tls_pki_md_cert_file_dest }}"

- name: Ensure key and cert directories exist
  ansible.builtin.include_tasks:
    file: create_directory.yml
  vars:
    dir_path: "{{ item }}"
  loop:
    - "{{ tls_pki_certs_dir }}"
    - "{{ tls_pki_keys_dir }}"

- name: Copy private key
  ansible.builtin.copy:
    src: "{{ tls_pki_md_key_file_local }}"
    dest: "{{ tls_pki_md_key_file_dest }}"
    owner: root
    group: root
    mode: '0600'

- name: Copy certificate
  ansible.builtin.copy:
    src: "{{ tls_pki_md_cert_file_local }}"
    dest: "{{ tls_pki_md_cert_file_dest }}"
    owner: root
    group: root
    mode: '0444'
