# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Copy CA certificate
  ansible.builtin.copy:
    src: "{{ tls_pki_ca_cert_file_src }}"
    dest: "{{ tls_pki_ca_cert_file_dest }}"
    owner: root
    group: root
    mode: '0444'
