# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Print upload details
  ansible.builtin.debug:
    msg:
      - "Uploading CA cert"
      - "   Source: {{ tls_pki_ca_cert_file_local }}"
      - "   Destination: {{ tls_pki_ca_cert_file_dest }}"


- name: Ensure CA certificate directory exists
  ansible.builtin.file:
    path: "{{ tls_pki_ca_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy CA certificate
  ansible.builtin.copy:
    src: "{{ tls_pki_ca_cert_file_local }}"
    dest: "{{ tls_pki_ca_cert_file_dest }}"
    owner: root
    group: root
    mode: '0444'

