# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Validate local pki directory is defined
  ansible.builtin.assert:
    that:
      - tls_pki_local_dir is defined
      - tls_pki_local_dir is not none
    fail_msg: Local pki directory (tls_pki_local_dir) is not defined in the inventory

- name: Stat the local pki directory
  ansible.builtin.stat:
    path: "{{ tls_pki_local_dir }}"
  register: tls_pki_local_dir_stat_result
  delegate_to: localhost
  become: false

- name: Validate local pki directory exists
  ansible.builtin.assert:
    that: tls_pki_local_dir_stat_result.stat.exists
    fail_msg: "Local pki directory '{{ tls_pki_local_dir }}' does not exist"
