# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Include tasks to validate variables
  ansible.builtin.include_tasks:
    file: validate_vars.yml
  tags: always

# -----------------
# CA (CSR with CA extensions -> self-signed CA cert)
# -----------------
- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ pki_ca_key_file_local }}"
    size: 4096
    type: RSA
    mode: '0600'

- name: Generate CA CSR with CA extensions
  community.crypto.openssl_csr:
    path: "{{ pki_ca_csr_file_local }}"
    privatekey_path: "{{ pki_ca_key_file_local }}"
    common_name: "{{ pki_ca_common_name }}"
    basic_constraints:
      - "CA:TRUE"
    key_usage:
      - keyCertSign
      - cRLSign

- name: Self-sign the CA CSR
  community.crypto.x509_certificate:
    path: "{{ pki_ca_cert_file_local }}"
    csr_path: "{{ pki_ca_csr_file_local }}"
    privatekey_path: "{{ pki_ca_key_file_local }}"
    provider: selfsigned
    # selfsigned_not_after: "+10y"
