# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Print upload details
  ansible.builtin.debug:
    msg:
      - "Uploading CA cert"
      - "   Source: {{ pki_ca_cert_file_local }}"
      - "   Destination: {{ pki_ca_cert_file_dest }}"

- name: Ensure CA certificate directory exists
  ansible.builtin.include_tasks:
    file: create_directory.yml
  vars:
    dir_path: "{{ pki_ca_certs_dir }}"

- name: Copy CA certificate
  ansible.builtin.copy:
    src: "{{ pki_ca_cert_file_local }}"
    dest: "{{ pki_ca_cert_file_dest }}"
    owner: root
    group: root
    mode: '0444'
