# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Print upload details
  ansible.builtin.debug:
    msg:
      - "Uploading key and cert"
      - "   Key source: {{ pki_key_file_local }}"
      - "   Key destination: {{ pki_key_file_dest }}"
      - "   Cert source: {{ pki_cert_file_local }}"
      - "   Cert destination: {{ pki_cert_file_dest }}"

- name: Ensure key and cert directories exist
  ansible.builtin.include_tasks:
    file: create_cert_directories.yml

- name: Copy private key
  ansible.builtin.copy:
    src: "{{ pki_key_file_local }}"
    dest: "{{ pki_key_file_dest }}"
    owner: root
    group: root
    mode: '0600'

- name: Copy certificate
  ansible.builtin.copy:
    src: "{{ pki_cert_file_local }}"
    dest: "{{ pki_cert_file_dest }}"
    owner: root
    group: root
    mode: '0444'
