# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true
  tasks: []

- name: Generate multi-domain cert for all hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate multi-domain cert for all hosts
      ansible.builtin.import_role:
        name: itential.pki.pki
        tasks_from: gen_multi_domain_cert
