# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Generate CA cert
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate CA cert
      ansible.builtin.import_role:
        name: itential.tls.tls
        tasks_from: gen_ca_cert
