# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Upload cert to hosts
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Upload cert to hosts
      ansible.builtin.import_role:
        name: itential.tls.tls
        tasks_from: upload_certs
